import { Instrument } from "./types"

export const instruments: Record<string, Instrument> = {
  "cg-wheatstone-30": {
    title: "CG Wheatstone 30",
    layout: [
      {
        push: "E3",
        pull: "F3",
        x: 30,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "1a",
        },
      },
      {
        push: "A3",
        pull: "Bb3",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "2a",
        },
      },
      {
        push: "C#4",
        pull: "D#4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "3a",
        },
      },
      {
        push: "A4",
        pull: "G4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "4a",
        },
      },
      {
        push: "G#4",
        pull: "Bb4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "5a",
        },
      },
      {
        push: "C#5",
        pull: "D#5",
        x: 50,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "1a",
        },
      },
      {
        push: "A5",
        pull: "G5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "2a",
        },
      },
      {
        push: "G#5",
        pull: "Bb5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "3a",
        },
      },
      {
        push: "C#6",
        pull: "D#6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "4a",
        },
      },
      {
        push: "A6",
        pull: "F6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "5a",
        },
      },
      {
        push: "C3",
        pull: "G3",
        x: 15,
        newRow: true,
        cooverNotationId: {
          hand: "left",
          id: "1",
        },
      },
      {
        push: "G3",
        pull: "B3",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "2",
        },
      },
      {
        push: "C4",
        pull: "D4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "3",
        },
      },
      {
        push: "E4",
        pull: "F4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "4",
        },
      },
      {
        push: "G4",
        pull: "A4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "5",
        },
      },
      {
        push: "C5",
        pull: "B4",
        x: 80,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "1",
        },
      },
      {
        push: "E5",
        pull: "D5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "2",
        },
      },
      {
        push: "G5",
        pull: "F5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "3",
        },
      },
      {
        push: "C6",
        pull: "A5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "4",
        },
      },
      {
        push: "E6",
        pull: "B5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "5",
        },
      },
      {
        push: "B3",
        pull: "A3",
        x: 0,
        newRow: true,
        cooverNotationId: {
          hand: "left",
          id: "6",
        },
      },
      {
        push: "D4",
        pull: "F#4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "7",
        },
      },
      {
        push: "G4",
        pull: "A4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "8",
        },
      },
      {
        push: "B4",
        pull: "C5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "9",
        },
      },
      {
        push: "D5",
        pull: "E5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "10",
        },
      },
      {
        push: "G5",
        pull: "F#5",
        x: 110,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "6",
        },
      },
      {
        push: "B5",
        pull: "A5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "7",
        },
      },
      {
        push: "D6",
        pull: "C6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "8",
        },
      },
      {
        push: "G6",
        pull: "E6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "9",
        },
      },
      {
        push: "B6",
        pull: "F#6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "10",
        },
      },
    ],
  },
  "cg-jeffries-30": {
    title: "CG Jeffries 30",
    layout: [
      {
        push: "E3",
        pull: "F3",
        x: 30,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "1a",
        },
      },
      {
        push: "A3",
        pull: "Bb3",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "2a",
        },
      },
      {
        push: "C#4",
        pull: "D#4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "3a",
        },
      },
      {
        push: "A4",
        pull: "G4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "4a",
        },
      },
      {
        push: "G#4",
        pull: "Bb4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "5a",
        },
      },
      {
        push: "D#5",
        pull: "C#5",
        x: 50,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "1a",
        },
      },
      {
        push: "C#5",
        pull: "D#5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "2a",
        },
      },
      {
        push: "G#5",
        pull: "G5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "3a",
        },
      },
      {
        push: "C#6",
        pull: "Bb5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "4a",
        },
      },
      {
        push: "A5",
        pull: "D6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "5a",
        },
      },
      {
        push: "C3",
        pull: "G3",
        x: 15,
        newRow: true,
        cooverNotationId: {
          hand: "left",
          id: "1",
        },
      },
      {
        push: "G3",
        pull: "B3",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "2",
        },
      },
      {
        push: "C4",
        pull: "D4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "3",
        },
      },
      {
        push: "E4",
        pull: "F4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "4",
        },
      },
      {
        push: "G4",
        pull: "A4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "5",
        },
      },
      {
        push: "C5",
        pull: "B4",
        x: 80,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "1",
        },
      },
      {
        push: "E5",
        pull: "D5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "2",
        },
      },
      {
        push: "G5",
        pull: "F5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "3",
        },
      },
      {
        push: "C6",
        pull: "A5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "4",
        },
      },
      {
        push: "E6",
        pull: "B5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "5",
        },
      },
      {
        push: "B3",
        pull: "A3",
        x: 0,
        newRow: true,
        cooverNotationId: {
          hand: "left",
          id: "6",
        },
      },
      {
        push: "D4",
        pull: "F#4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "7",
        },
      },
      {
        push: "G4",
        pull: "A4",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "8",
        },
      },
      {
        push: "B4",
        pull: "C5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "9",
        },
      },
      {
        push: "D5",
        pull: "E5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "left",
          id: "10",
        },
      },
      {
        push: "G5",
        pull: "F#5",
        x: 110,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "6",
        },
      },
      {
        push: "B5",
        pull: "A5",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "7",
        },
      },
      {
        push: "D6",
        pull: "C6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "8",
        },
      },
      {
        push: "G6",
        pull: "E6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "9",
        },
      },
      {
        push: "B6",
        pull: "F#6",
        x: 0,
        newRow: false,
        cooverNotationId: {
          hand: "right",
          id: "10",
        },
      },
    ],
  },
  "cg-wheatstone-40": {
    title: "CG Wheatstone 40",
    layout: [
      { push: "E3", pull: "F3", x: 30, newRow: false },
      { push: "A3", pull: "Bb3", x: 0, newRow: false },
      { push: "C#4", pull: "D#4", x: 0, newRow: false },
      { push: "A4", pull: "G4", x: 0, newRow: false },
      { push: "G#4", pull: "Bb4", x: 0, newRow: false },
      { push: "F#4", pull: "C#4", x: 0, newRow: false },
      { push: "F#5", pull: "C#5", x: 50, newRow: false },
      { push: "C#5", pull: "D#5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "G#5", pull: "Bb5", x: 0, newRow: false },
      { push: "C#6", pull: "D#6", x: 0, newRow: false },
      { push: "A6", pull: "F6", x: 0, newRow: false },
      { push: "C7", pull: "D6", x: 0, newRow: false },
      { push: "C3", pull: "G3", x: 15, newRow: true },
      { push: "G3", pull: "B3", x: 0, newRow: false },
      { push: "C4", pull: "D4", x: 0, newRow: false },
      { push: "E4", pull: "F4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "Bb4", pull: "C#5", x: 0, newRow: false },
      { push: "F5", pull: "G4", x: 80, newRow: false },
      { push: "C5", pull: "B4", x: 0, newRow: false },
      { push: "E5", pull: "D5", x: 0, newRow: false },
      { push: "G5", pull: "F5", x: 0, newRow: false },
      { push: "C6", pull: "A5", x: 0, newRow: false },
      { push: "E6", pull: "B5", x: 0, newRow: false },
      { push: "B3", pull: "A3", x: 0, newRow: true },
      { push: "D4", pull: "F#4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "B4", pull: "C5", x: 0, newRow: false },
      { push: "D5", pull: "E5", x: 0, newRow: false },
      { push: "F4", pull: "G#4", x: 0, newRow: false },
      { push: "Bb5", pull: "G#5", x: 110, newRow: false },
      { push: "G5", pull: "F#5", x: 0, newRow: false },
      { push: "B5", pull: "A5", x: 0, newRow: false },
      { push: "D6", pull: "C6", x: 0, newRow: false },
      { push: "G6", pull: "E6", x: 0, newRow: false },
      { push: "B6", pull: "F#6", x: 0, newRow: false },
      { push: "C4", pull: "C4", x: 330, newRow: true },
      { push: "D#5", pull: "A4", x: 160, newRow: false },
      { push: "D5", pull: "E5", x: 55, newRow: false },
    ],
  },
  "cg-jeffries-38": {
    title: "CG Jeffries 38",
    layout: [
      { push: "E3", pull: "F3", x: 30, newRow: false },
      { push: "A3", pull: "Bb3", x: 0, newRow: false },
      { push: "C#4", pull: "D#4", x: 0, newRow: false },
      { push: "A4", pull: "G4", x: 0, newRow: false },
      { push: "G#4", pull: "Bb4", x: 0, newRow: false },
      { push: "D#5", pull: "C#5", x: 170, newRow: false },
      { push: "C#5", pull: "D#5", x: 0, newRow: false },
      { push: "G#5", pull: "G5", x: 0, newRow: false },
      { push: "C#6", pull: "Bb5", x: 0, newRow: false },
      { push: "A5", pull: "D6", x: 0, newRow: false },
      { push: "C3", pull: "G3", x: 15, newRow: true },
      { push: "G3", pull: "B3", x: 0, newRow: false },
      { push: "C4", pull: "D4", x: 0, newRow: false },
      { push: "E4", pull: "F4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "Bb4", pull: "Bb3", x: 0, newRow: false },
      { push: "F#5", pull: "A4", x: 80, newRow: false },
      { push: "C5", pull: "B4", x: 0, newRow: false },
      { push: "E5", pull: "D5", x: 0, newRow: false },
      { push: "G5", pull: "F5", x: 0, newRow: false },
      { push: "C6", pull: "A5", x: 0, newRow: false },
      { push: "E6", pull: "B5", x: 0, newRow: false },
      { push: "F5", pull: "E5", x: 0, newRow: false },
      { push: "B3", pull: "A3", x: 0, newRow: true },
      { push: "D4", pull: "F#4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "B4", pull: "C5", x: 0, newRow: false },
      { push: "D5", pull: "E5", x: 0, newRow: false },
      { push: "F#4", pull: "G#4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 110, newRow: false },
      { push: "G5", pull: "F#5", x: 0, newRow: false },
      { push: "B5", pull: "A5", x: 0, newRow: false },
      { push: "D6", pull: "C6", x: 0, newRow: false },
      { push: "G6", pull: "E6", x: 0, newRow: false },
      { push: "B6", pull: "F#6", x: 0, newRow: false },
      { push: "D#4", pull: "E4", x: 145, newRow: true },
      { push: "C4", pull: "C4", x: 125, newRow: false },
      { push: "F#6", pull: "F6", x: 220, newRow: false },
    ],
  },
  "gd-wheatstone-30": {
    title: "GD Wheatstone 30",
    layout: [
      { push: "B2", pull: "C3", x: 30, newRow: false },
      { push: "E3", pull: "F3", x: 0, newRow: false },
      { push: "G#3", pull: "Bb3", x: 0, newRow: false },
      { push: "E4", pull: "D4", x: 0, newRow: false },
      { push: "D#4", pull: "F4", x: 0, newRow: false },
      { push: "G#4", pull: "Bb4", x: 50, newRow: false },
      { push: "E5", pull: "D5", x: 0, newRow: false },
      { push: "D#5", pull: "F5", x: 0, newRow: false },
      { push: "G#5", pull: "Bb5", x: 0, newRow: false },
      { push: "E6", pull: "C6", x: 0, newRow: false },
      { push: "G2", pull: "D3", x: 15, newRow: true },
      { push: "D3", pull: "F#3", x: 0, newRow: false },
      { push: "G3", pull: "A3", x: 0, newRow: false },
      { push: "B3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "G4", pull: "F#4", x: 80, newRow: false },
      { push: "B4", pull: "A4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "G5", pull: "E5", x: 0, newRow: false },
      { push: "B5", pull: "F#5", x: 0, newRow: false },
      { push: "F#3", pull: "E3", x: 0, newRow: true },
      { push: "A3", pull: "C#4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F#4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "B4", x: 0, newRow: false },
      { push: "D5", pull: "C#5", x: 110, newRow: false },
      { push: "F#5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "B5", x: 0, newRow: false },
      { push: "F#6", pull: "C#6", x: 0, newRow: false },
    ],
  },
  "gd-jeffries-30": {
    title: "GD Jeffries 30",
    layout: [
      { push: "B2", pull: "C3", x: 30, newRow: false },
      { push: "E3", pull: "F3", x: 0, newRow: false },
      { push: "G#3", pull: "Bb3", x: 0, newRow: false },
      { push: "E4", pull: "D4", x: 0, newRow: false },
      { push: "D#4", pull: "F4", x: 0, newRow: false },
      { push: "Bb4", pull: "G#4", x: 50, newRow: false },
      { push: "G#4", pull: "Bb4", x: 0, newRow: false },
      { push: "D#5", pull: "D5", x: 0, newRow: false },
      { push: "G#5", pull: "F5", x: 0, newRow: false },
      { push: "Bb5", pull: "A5", x: 0, newRow: false },
      { push: "G2", pull: "D3", x: 15, newRow: true },
      { push: "D3", pull: "F#3", x: 0, newRow: false },
      { push: "G3", pull: "A3", x: 0, newRow: false },
      { push: "B3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "G4", pull: "F#4", x: 80, newRow: false },
      { push: "B4", pull: "A4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "G5", pull: "E5", x: 0, newRow: false },
      { push: "B5", pull: "F#5", x: 0, newRow: false },
      { push: "F#3", pull: "E3", x: 0, newRow: true },
      { push: "A3", pull: "C#4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F#4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "B4", x: 0, newRow: false },
      { push: "D5", pull: "C#5", x: 110, newRow: false },
      { push: "F#5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "B5", x: 0, newRow: false },
      { push: "F#6", pull: "C#6", x: 0, newRow: false },
    ],
  },
  "gd-wheatstone-40": {
    title: "GD Wheatstone 40",
    layout: [
      { push: "B2", pull: "C3", x: 30, newRow: false },
      { push: "E3", pull: "F3", x: 0, newRow: false },
      { push: "G#3", pull: "Bb3", x: 0, newRow: false },
      { push: "E4", pull: "D4", x: 0, newRow: false },
      { push: "D#4", pull: "F4", x: 0, newRow: false },
      { push: "C#4", pull: "G#3", x: 0, newRow: false },
      { push: "C#5", pull: "G#4", x: 50, newRow: false },
      { push: "G#4", pull: "Bb4", x: 0, newRow: false },
      { push: "E5", pull: "D5", x: 0, newRow: false },
      { push: "D#5", pull: "F5", x: 0, newRow: false },
      { push: "G#5", pull: "Bb5", x: 0, newRow: false },
      { push: "E6", pull: "C6", x: 0, newRow: false },
      { push: "G6", pull: "A5", x: 0, newRow: false },
      { push: "G2", pull: "D3", x: 15, newRow: true },
      { push: "D3", pull: "F#3", x: 0, newRow: false },
      { push: "G3", pull: "A3", x: 0, newRow: false },
      { push: "B3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F4", pull: "G#4", x: 0, newRow: false },
      { push: "C5", pull: "D4", x: 80, newRow: false },
      { push: "G4", pull: "F#4", x: 0, newRow: false },
      { push: "B4", pull: "A4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "G5", pull: "E5", x: 0, newRow: false },
      { push: "B5", pull: "F#5", x: 0, newRow: false },
      { push: "F#3", pull: "E3", x: 0, newRow: true },
      { push: "A3", pull: "C#4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F#4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "B4", x: 0, newRow: false },
      { push: "C4", pull: "D#4", x: 0, newRow: false },
      { push: "F5", pull: "D#5", x: 110, newRow: false },
      { push: "D5", pull: "C#5", x: 0, newRow: false },
      { push: "F#5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "B5", x: 0, newRow: false },
      { push: "F#6", pull: "C#6", x: 0, newRow: false },
      { push: "G3", pull: "G3", x: 330, newRow: true },
      { push: "Bb4", pull: "E4", x: 160, newRow: false },
      { push: "A4", pull: "B4", x: 55, newRow: false },
    ],
  },
  "gd-jeffries-38": {
    title: "GD Jeffries 38",
    layout: [
      { push: "B2", pull: "C3", x: 30, newRow: false },
      { push: "E3", pull: "F3", x: 0, newRow: false },
      { push: "G#3", pull: "Bb3", x: 0, newRow: false },
      { push: "E4", pull: "D4", x: 0, newRow: false },
      { push: "D#4", pull: "F4", x: 0, newRow: false },
      { push: "Bb4", pull: "G#4", x: 170, newRow: false },
      { push: "G#4", pull: "Bb4", x: 0, newRow: false },
      { push: "D#5", pull: "D5", x: 0, newRow: false },
      { push: "G#5", pull: "F5", x: 0, newRow: false },
      { push: "Bb5", pull: "A5", x: 0, newRow: false },
      { push: "G2", pull: "D3", x: 15, newRow: true },
      { push: "D3", pull: "F#3", x: 0, newRow: false },
      { push: "G3", pull: "A3", x: 0, newRow: false },
      { push: "B3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F4", pull: "F3", x: 0, newRow: false },
      { push: "C#5", pull: "E4", x: 80, newRow: false },
      { push: "G4", pull: "F#4", x: 0, newRow: false },
      { push: "B4", pull: "A4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "G5", pull: "E5", x: 0, newRow: false },
      { push: "B5", pull: "F#5", x: 0, newRow: false },
      { push: "C5", pull: "B4", x: 0, newRow: false },
      { push: "F#3", pull: "E3", x: 0, newRow: true },
      { push: "A3", pull: "C#4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F#4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "B4", x: 0, newRow: false },
      { push: "C#4", pull: "D#4", x: 0, newRow: false },
      { push: "A4", pull: "G4", x: 110, newRow: false },
      { push: "D5", pull: "C#5", x: 0, newRow: false },
      { push: "F#5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "B5", x: 0, newRow: false },
      { push: "F#6", pull: "C#6", x: 0, newRow: false },
      { push: "Bb3", pull: "B3", x: 145, newRow: true },
      { push: "G3", pull: "G3", x: 125, newRow: false },
      { push: "C#6", pull: "C6", x: 220, newRow: false },
    ],
  },
  "bbf-wheatstone-30": {
    title: "BbF Wheatstone 30",
    layout: [
      { push: "D3", pull: "D#3", x: 30, newRow: false },
      { push: "G3", pull: "G#3", x: 0, newRow: false },
      { push: "B3", pull: "C#4", x: 0, newRow: false },
      { push: "G4", pull: "F4", x: 0, newRow: false },
      { push: "F#4", pull: "G#4", x: 0, newRow: false },
      { push: "B4", pull: "C#5", x: 50, newRow: false },
      { push: "G5", pull: "F5", x: 0, newRow: false },
      { push: "F#5", pull: "G#5", x: 0, newRow: false },
      { push: "B5", pull: "C#6", x: 0, newRow: false },
      { push: "G6", pull: "D#6", x: 0, newRow: false },
      { push: "Bb2", pull: "F3", x: 15, newRow: true },
      { push: "F3", pull: "A3", x: 0, newRow: false },
      { push: "Bb3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "D#4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "Bb4", pull: "A4", x: 80, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "F5", pull: "D#5", x: 0, newRow: false },
      { push: "Bb5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "A5", x: 0, newRow: false },
      { push: "A3", pull: "G3", x: 0, newRow: true },
      { push: "C4", pull: "E4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "Bb4", x: 0, newRow: false },
      { push: "C5", pull: "D5", x: 0, newRow: false },
      { push: "F5", pull: "E5", x: 110, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "C6", pull: "Bb5", x: 0, newRow: false },
      { push: "F6", pull: "D6", x: 0, newRow: false },
      { push: "A6", pull: "E6", x: 0, newRow: false },
    ],
  },
  "bbf-jeffries-30": {
    title: "BbF Jeffries 30",
    layout: [
      { push: "D3", pull: "D#3", x: 30, newRow: false },
      { push: "G3", pull: "G#3", x: 0, newRow: false },
      { push: "B3", pull: "C#4", x: 0, newRow: false },
      { push: "G4", pull: "F4", x: 0, newRow: false },
      { push: "F#4", pull: "G#4", x: 0, newRow: false },
      { push: "C#5", pull: "B4", x: 50, newRow: false },
      { push: "B4", pull: "C#5", x: 0, newRow: false },
      { push: "F#5", pull: "F5", x: 0, newRow: false },
      { push: "B5", pull: "G#5", x: 0, newRow: false },
      { push: "C#6", pull: "C6", x: 0, newRow: false },
      { push: "Bb2", pull: "F3", x: 15, newRow: true },
      { push: "F3", pull: "A3", x: 0, newRow: false },
      { push: "Bb3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "D#4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "Bb4", pull: "A4", x: 80, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "F5", pull: "D#5", x: 0, newRow: false },
      { push: "Bb5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "A5", x: 0, newRow: false },
      { push: "A3", pull: "G3", x: 0, newRow: true },
      { push: "C4", pull: "E4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "Bb4", x: 0, newRow: false },
      { push: "C5", pull: "D5", x: 0, newRow: false },
      { push: "F5", pull: "E5", x: 110, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "C6", pull: "Bb5", x: 0, newRow: false },
      { push: "F6", pull: "D6", x: 0, newRow: false },
      { push: "A6", pull: "E6", x: 0, newRow: false },
    ],
  },
  "bbf-wheatstone-40": {
    title: "BbF Wheatstone 40",
    layout: [
      { push: "D3", pull: "D#3", x: 30, newRow: false },
      { push: "G3", pull: "G#3", x: 0, newRow: false },
      { push: "B3", pull: "C#4", x: 0, newRow: false },
      { push: "G4", pull: "F4", x: 0, newRow: false },
      { push: "F#4", pull: "G#4", x: 0, newRow: false },
      { push: "E4", pull: "B3", x: 0, newRow: false },
      { push: "E5", pull: "B4", x: 50, newRow: false },
      { push: "B4", pull: "C#5", x: 0, newRow: false },
      { push: "G5", pull: "F5", x: 0, newRow: false },
      { push: "F#5", pull: "G#5", x: 0, newRow: false },
      { push: "B5", pull: "C#6", x: 0, newRow: false },
      { push: "G6", pull: "D#6", x: 0, newRow: false },
      { push: "Bb6", pull: "C6", x: 0, newRow: false },
      { push: "Bb2", pull: "F3", x: 15, newRow: true },
      { push: "F3", pull: "A3", x: 0, newRow: false },
      { push: "Bb3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "D#4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "G#4", pull: "B4", x: 0, newRow: false },
      { push: "D#5", pull: "F4", x: 80, newRow: false },
      { push: "Bb4", pull: "A4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "F5", pull: "D#5", x: 0, newRow: false },
      { push: "Bb5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "A5", x: 0, newRow: false },
      { push: "A3", pull: "G3", x: 0, newRow: true },
      { push: "C4", pull: "E4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "Bb4", x: 0, newRow: false },
      { push: "C5", pull: "D5", x: 0, newRow: false },
      { push: "D#4", pull: "F#4", x: 0, newRow: false },
      { push: "G#5", pull: "F#5", x: 110, newRow: false },
      { push: "F5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "C6", pull: "Bb5", x: 0, newRow: false },
      { push: "F6", pull: "D6", x: 0, newRow: false },
      { push: "A6", pull: "E6", x: 0, newRow: false },
      { push: "Bb3", pull: "Bb3", x: 330, newRow: true },
      { push: "C#5", pull: "G4", x: 160, newRow: false },
      { push: "C5", pull: "D5", x: 55, newRow: false },
    ],
  },
  "bbf-jeffries-38": {
    title: "BbF Jeffries 38",
    layout: [
      { push: "D3", pull: "D#3", x: 30, newRow: false },
      { push: "G3", pull: "G#3", x: 0, newRow: false },
      { push: "B3", pull: "C#4", x: 0, newRow: false },
      { push: "G4", pull: "F4", x: 0, newRow: false },
      { push: "F#4", pull: "G#4", x: 0, newRow: false },
      { push: "C#5", pull: "B4", x: 170, newRow: false },
      { push: "B4", pull: "C#5", x: 0, newRow: false },
      { push: "F#5", pull: "F5", x: 0, newRow: false },
      { push: "B5", pull: "G#5", x: 0, newRow: false },
      { push: "C#6", pull: "C6", x: 0, newRow: false },
      { push: "Bb2", pull: "F3", x: 15, newRow: true },
      { push: "F3", pull: "A3", x: 0, newRow: false },
      { push: "Bb3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "D#4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "G#4", pull: "G#3", x: 0, newRow: false },
      { push: "E5", pull: "G4", x: 80, newRow: false },
      { push: "Bb4", pull: "A4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "F5", pull: "D#5", x: 0, newRow: false },
      { push: "Bb5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "A5", x: 0, newRow: false },
      { push: "D#5", pull: "D5", x: 0, newRow: false },
      { push: "A3", pull: "G3", x: 0, newRow: true },
      { push: "C4", pull: "E4", x: 0, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "Bb4", x: 0, newRow: false },
      { push: "C5", pull: "D5", x: 0, newRow: false },
      { push: "E4", pull: "F#4", x: 0, newRow: false },
      { push: "C5", pull: "Bb4", x: 110, newRow: false },
      { push: "F5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "C6", pull: "Bb5", x: 0, newRow: false },
      { push: "F6", pull: "D6", x: 0, newRow: false },
      { push: "A6", pull: "E6", x: 0, newRow: false },
      { push: "C#4", pull: "D4", x: 145, newRow: true },
      { push: "Bb3", pull: "Bb3", x: 125, newRow: false },
      { push: "E6", pull: "D#6", x: 220, newRow: false },
    ],
  },
  jones: {
    title: 'G. Jones "Improved Anglo"',
    layout: [
      { push: "E3", pull: "F3", x: 30, newRow: false },
      { push: "A3", pull: "A3", x: 0, newRow: false },
      { push: "G#3", pull: "Bb3", x: 0, newRow: false },
      { push: "C#4", pull: "C#4", x: 0, newRow: false },
      { push: "D#4", pull: "D#4", x: 0, newRow: false },
      { push: "G#4", pull: "G#4", x: 0, newRow: false },
      { push: "Bb4", pull: "Bb4", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 70, newRow: false },
      { push: "C#5", pull: "C#5", x: 0, newRow: false },
      { push: "D#5", pull: "D#5", x: 0, newRow: false },
      { push: "G#5", pull: "G#5", x: 0, newRow: false },
      { push: "Bb5", pull: "Bb5", x: 0, newRow: false },
      { push: "C#6", pull: "C#6", x: 0, newRow: false },
      { push: "D#6", pull: "D6", x: 0, newRow: false },
      { push: "Bb3", pull: "C4", x: 0, newRow: true },
      { push: "C3", pull: "G3", x: 0, newRow: false },
      { push: "G3", pull: "B3", x: 0, newRow: false },
      { push: "C4", pull: "D4", x: 0, newRow: false },
      { push: "E4", pull: "F4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "A4", pull: "G4", x: 0, newRow: false },
      { push: "F#5", pull: "F#5", x: 70, newRow: false },
      { push: "C5", pull: "B4", x: 0, newRow: false },
      { push: "E5", pull: "D5", x: 0, newRow: false },
      { push: "G5", pull: "F5", x: 0, newRow: false },
      { push: "C6", pull: "A5", x: 0, newRow: false },
      { push: "E6", pull: "B5", x: 0, newRow: false },
      { push: "C7", pull: "F6", x: 0, newRow: false },
      { push: "B3", pull: "D4", x: 30, newRow: true },
      { push: "D4", pull: "F#4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "B4", pull: "C5", x: 0, newRow: false },
      { push: "D5", pull: "E5", x: 0, newRow: false },
      { push: "F4", pull: "E4", x: 0, newRow: false },
      { push: "F#4", pull: "F#4", x: 0, newRow: false },
      { push: "F5", pull: "F5", x: 70, newRow: false },
      { push: "G5", pull: "F#5", x: 0, newRow: false },
      { push: "B5", pull: "A5", x: 0, newRow: false },
      { push: "D6", pull: "C6", x: 0, newRow: false },
      { push: "G6", pull: "E6", x: 0, newRow: false },
      { push: "B6", pull: "F#6", x: 0, newRow: false },
      { push: "G#6", pull: "A6", x: 0, newRow: false },
    ],
  },
  "cg-20": {
    title: "CG 20",
    layout: [
      { push: "C3", pull: "G3", x: 20, newRow: false },
      { push: "G3", pull: "B3", x: 0, newRow: false },
      { push: "C4", pull: "D4", x: 0, newRow: false },
      { push: "E4", pull: "F4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "C5", pull: "B4", x: 70, newRow: false },
      { push: "E5", pull: "D5", x: 0, newRow: false },
      { push: "G5", pull: "F5", x: 0, newRow: false },
      { push: "C6", pull: "A5", x: 0, newRow: false },
      { push: "E6", pull: "B5", x: 0, newRow: false },
      { push: "G3", pull: "D4", x: 0, newRow: true },
      { push: "D4", pull: "F#4", x: 0, newRow: false },
      { push: "G4", pull: "A4", x: 0, newRow: false },
      { push: "B4", pull: "C5", x: 0, newRow: false },
      { push: "D5", pull: "E5", x: 0, newRow: false },
      { push: "G5", pull: "F#5", x: 110, newRow: false },
      { push: "B5", pull: "A5", x: 0, newRow: false },
      { push: "D6", pull: "C6", x: 0, newRow: false },
      { push: "G6", pull: "E6", x: 0, newRow: false },
      { push: "B6", pull: "F#6", x: 0, newRow: false },
    ],
  },
  "gd-20": {
    title: "GD 20",
    layout: [
      { push: "G2", pull: "D3", x: 20, newRow: false },
      { push: "D3", pull: "F#3", x: 0, newRow: false },
      { push: "G3", pull: "A3", x: 0, newRow: false },
      { push: "B3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "G4", pull: "F#4", x: 70, newRow: false },
      { push: "B4", pull: "A4", x: 0, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "G5", pull: "E5", x: 0, newRow: false },
      { push: "B5", pull: "F#5", x: 0, newRow: false },
      { push: "D3", pull: "A3", x: 0, newRow: true },
      { push: "A3", pull: "C#4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F#4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "B4", x: 0, newRow: false },
      { push: "D5", pull: "C#5", x: 110, newRow: false },
      { push: "F#5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "B5", x: 0, newRow: false },
      { push: "F#6", pull: "C#6", x: 0, newRow: false },
    ],
  },
  "da-20": {
    title: "DA 20",
    layout: [
      { push: "D3", pull: "A3", x: 20, newRow: false },
      { push: "A3", pull: "C#4", x: 0, newRow: false },
      { push: "D4", pull: "E4", x: 0, newRow: false },
      { push: "F#4", pull: "G4", x: 0, newRow: false },
      { push: "A4", pull: "B4", x: 0, newRow: false },
      { push: "D5", pull: "C#5", x: 70, newRow: false },
      { push: "F#5", pull: "E5", x: 0, newRow: false },
      { push: "A5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "B5", x: 0, newRow: false },
      { push: "F#6", pull: "C#6", x: 0, newRow: false },
      { push: "A3", pull: "E4", x: 0, newRow: true },
      { push: "E4", pull: "G#4", x: 0, newRow: false },
      { push: "A4", pull: "B4", x: 0, newRow: false },
      { push: "C#5", pull: "D5", x: 0, newRow: false },
      { push: "E5", pull: "F#5", x: 0, newRow: false },
      { push: "A5", pull: "G#5", x: 110, newRow: false },
      { push: "C#6", pull: "B5", x: 0, newRow: false },
      { push: "E6", pull: "D6", x: 0, newRow: false },
      { push: "A6", pull: "F#6", x: 0, newRow: false },
      { push: "C#7", pull: "G#6", x: 0, newRow: false },
    ],
  },
  squashbox: {
    title: "Zulu Squashbox",
    layout: [
      { push: "D#2", pull: "Bb2", x: 20, newRow: false },
      { push: "Bb2", pull: "D3", x: 0, newRow: false },
      { push: "D#3", pull: "F3", x: 0, newRow: false },
      { push: "G3", pull: "G#3", x: 0, newRow: false },
      { push: "Bb3", pull: "C4", x: 0, newRow: false },
      { push: "D4", pull: "D#4", x: 70, newRow: false },
      { push: "F4", pull: "G4", x: 0, newRow: false },
      { push: "G#4", pull: "Bb4", x: 0, newRow: false },
      { push: "C5", pull: "D5", x: 0, newRow: false },
      { push: "D5", pull: "G5", x: 0, newRow: false },
      { push: "F3", pull: "Bb2", x: 0, newRow: true },
      { push: "A3", pull: "F3", x: 0, newRow: false },
      { push: "C4", pull: "Bb3", x: 0, newRow: false },
      { push: "D#4", pull: "D4", x: 0, newRow: false },
      { push: "G4", pull: "F4", x: 0, newRow: false },
      { push: "Bb4", pull: "A4", x: 110, newRow: false },
      { push: "D5", pull: "C5", x: 0, newRow: false },
      { push: "F5", pull: "D#5", x: 0, newRow: false },
      { push: "Bb5", pull: "G5", x: 0, newRow: false },
      { push: "D6", pull: "A5", x: 0, newRow: false },
    ],
  },
} as const
