export default {
  en: {
    profile: "Profile",
    "edit-profile": "Edit Profile",
    "signin-to-edit-profile": "Please sign in to edit your profile",
    "sign-in": "Sign In",
    "sign-out": "Sign Out",
    "success-sign-in": "Successfully signed in",
    "display-name": "Display Name",
    bio: "Bio",
    tracks: "Tracks",
    "recent-tracks": "Recent Tracks",
    "play-count": "plays",
    "play-count-1": "play",
    "song-not-found": "Song not found",
    download: "Download",
    share: "Share",
    save: "Save",
    close: "Close",
    copy: "Copy",
    copied: "Copied",
    "created-at": "Created at",
    "published-at": "Published at",
    "updated-at": "Updated at",
    "user-not-found": "User not found",
    "create-new": "Create New",
    "untitled-song": "Untitled song",
  },
  ja: {
    profile: "プロフィール",
    "edit-profile": "プロフィールを編集",
    "signin-to-edit-profile":
      "プロフィールを編集するにはサインインしてください",
    "sign-in": "サインイン",
    "sign-out": "サインアウト",
    "success-sign-in": "サインインに成功しました",
    "display-name": "表示名",
    bio: "自己紹介",
    tracks: "トラック",
    "recent-tracks": "最近の曲",
    "play-count": "回再生",
    "play-count-1": "回再生",
    "song-not-found": "曲が見つかりません",
    download: "ダウンロード",
    share: "共有",
    save: "保存",
    close: "閉じる",
    copy: "コピー",
    copied: "コピーしました",
    "created-at": "作成日 ",
    "published-at": "公開日 ",
    "updated-at": "更新日 ",
    "user-not-found": "ユーザーが見つかりません",
    "create-new": "新規作成",
    "untitled-song": "無題の楽曲",
  },
  "zh-Hans": {
    profile: "Profile",
    "edit-profile": "Edit Profile",
    "signin-to-edit-profile": "Please sign in to edit your profile",
    "sign-in": "登录",
    "sign-out": "Sign Out",
    "success-sign-in": "登录成功",
    "display-name": "Display Name",
    bio: "Bio",
    tracks: "Tracks",
    "recent-tracks": "Recent Tracks",
    "play-count": "plays",
    "play-count-1": "play",
    "song-not-found": "Song not found",
    download: "Download",
    share: "Share",
    save: "Save",
    close: "关闭",
    copy: "拷贝",
    copied: "Copied",
    "created-at": "Created at",
    "published-at": "Published at",
    "updated-at": "Updated at",
    "user-not-found": "User not found",
    "create-new": "Create New",
    "untitled-song": "未命名",
  },
  "zh-Hant": {
    profile: "個人資訊",
    "edit-profile": "編輯個人資訊",
    "signin-to-edit-profile": "登入以編輯個人資訊",
    "sign-in": "登入",
    "sign-out": "登出",
    "success-sign-in": "登入成功",
    "display-name": "顯示名稱",
    bio: "自我介紹",
    tracks: "音軌",
    "recent-tracks": "最近的曲目",
    "play-count": "plays",
    "play-count-1": "play",
    "song-not-found": "Song not found",
    download: "Download",
    share: "Share",
    save: "儲存",
    close: "關閉",
    copy: "複製",
    copied: "Copied",
    "created-at": "Created at",
    "published-at": "Published at",
    "updated-at": "Updated at",
    "user-not-found": "User not found",
    "create-new": "Create New",
    "untitled-song": "未命名",
  },
} as const
